[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "asb"
version = "@project.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "../native/build/libs/azure-service-bus-native-@project.version@.jar"
groupId = "org.ballerinax"
artifactId = "asb-native"
module = "asb-native" 
version = "@project.version@"
