name: Deployment

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Java Environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: 2201.7.0

      # Grant execute permission to the gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the project with Gradle
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: |
          ./gradlew build -x test

      # Perform Trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          skip-dirs: 'gradle/'
          format: 'table'
          timeout: '10m0s'
          exit-code: '1'

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
          TOPIC_NAME: ${{ secrets.TOPIC_NAME }}
          SUBSCRIPTION_NAME1: ${{ secrets.SUBSCRIPTION_NAME1 }}
          SUBSCRIPTION_NAME2: ${{ secrets.SUBSCRIPTION_NAME2 }}
          SUBSCRIPTION_NAME3: ${{ secrets.SUBSCRIPTION_NAME3 }}

      # Push to Ballerina Central
      - name: Ballerina Push
        run: bal push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          WORKING_DIR: ./ballerina
          JAVA_HOME: /usr/lib/jvm/default-jvm
